### ISSUE TITLE
Usage of deprecated API `ActionUpdateThread.OLD_EDT`

### ISSUE THREAD

**Issue by poirier** [sadv1r/ansible-vault-editor-idea-plugin#280]
Ansible Vault Editor plugin 1.2.1.

Error from PyCharm 2024.1 yesterday:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'ru.sadv1r.idea.plugin.ansible.vault.editor.action.FileEncryptAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: ru.sadv1r.ansible-vault-editor-idea-plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

**Comment by siebrand** [comment]
Please address this issue before the plugin may break in a future version.
