### ISSUE TITLE
decrypt() should gracefully handle empty 'encrypted' string parameter

### ISSUE THREAD

**Issue by TSheahanAtSpirit** [sadv1r/ansible-vault-editor-idea-plugin#57]
PyCharm reports errors in Ansible Vault Editor 1.7 such as:
```java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 8
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at ru.sadv1r.ansible.vault.VaultHandler.decrypt(VaultHandler.java:44)
	at ru.sadv1r.idea.plugin.ansible.vault.editor.FileVault.getDecryptedData(FileVault.kt:26)
	at ru.sadv1r.idea.plugin.ansible.vault.editor.ui.VaultPasswordDialog.getDecryptedOrEmpty(VaultPasswordDialog.kt:85)
	at ru.sadv1r.idea.plugin.ansible.vault.editor.ui.VaultPasswordDialog.doOKAction(VaultPasswordDialog.kt:62)
	at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1881)
...
```

This will happen when adding an empty file.yml, setting basic contents like 'abc: 123' and then attempting Tools -> Ansible Vault Editor -> &lt;supply password and decrypt&gt;

The decrypt() method in VaultHandler.java should gracefully handle the case where `encrypted.indexOf(LINE_BREAK);` returns -1, instead of throwing an exception up to Pycharm

https://github.com/sadv1r/ansible-vault-editor-idea-plugin/blob/f9b79f22d4bc2f65579344921e0b3aa1b90aeb06/src/main/java/ru/sadv1r/ansible/vault/VaultHandler.java#L44

**Comment by sadv1r** [comment]
Fixed in #59. Could you update to the new version?
